### ISSUE TITLE
Uncaught TypeError: this.editor.getPath is not a function

### ISSUE THREAD

**Issue by joshluongo** [mihaliak/php-refactoring#2]
[Enter steps to reproduce below:]
1. Attempt to refactor code via extracting.

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.6
**Thrown From**: [php-refactoring](https://github.com/mihaliak/php-refactoring) package, v1.4.0
### Stack Trace

Uncaught TypeError: this.editor.getPath is not a function

```
At /Users/Josh/.atom/packages/php-refactoring/lib/php-refactoring.coffee:73

TypeError: this.editor.getPath is not a function
    at Object.module.exports.PhpRefactoring.extractMethod (/Users/Josh/.atom/packages/php-refactoring/lib/php-refactoring.coffee:73:24)
    at Object.module.exports.PhpRefactoring.handleConfirm (/Users/Josh/.atom/packages/php-refactoring/lib/php-refactoring.coffee:61:10)
    at atom-text-editor.<anonymous> (/Users/Josh/.atom/packages/php-refactoring/lib/php-refactoring.coffee:55:102)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -1:21.3.0 php-refactoring:extract (atom-text-editor.editor)
 37x -1:15.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:54.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:46.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:46.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:32.1.0 core:undo (atom-text-editor.editor.is-focused)
     -0:30 core:save (atom-text-editor.editor.is-focused)
     -0:26.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:26.1.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:21.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:19.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:19.8.0 php-refactoring:extract (atom-text-editor.editor)
  9x -0:13.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  9x -0:03.8.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -0:02.2.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "an-old-hope-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
an-old-hope-syntax, v0.5.0
language-blade, v0.25.3
language-htaccess, v0.1.1
language-ini, v1.16.0
minimap, v4.24.7
php-refactoring, v1.4.0
pretty-json, v1.4.4

# Dev
No dev packages
```

**Comment by webhacking** [comment]
I got same issue

**Comment by pmgouveia** [comment]
yeap

**Comment by mihaliak** [comment]
This package is not maintained anymore, sorry.
